version: 1
update_configs:
  - package_manager: "docker"
    directory: "python-tools"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "detect-secrets"
    update_schedule: "weekly"
